version: "3.7"

services:
  angular:
    build: frontend
    ports:
      - 3000:3000

  express:
    build: backend
    ports:
      - 5000:5000
    links:
      - database

  mongo:
    image: mongo
    ports:
      - 27017:27017