# I only kept Dockerfile.
# Codebase itself was deleted because all the dependencies were VERY outdated, a lot of vulnerabilities.
# No code to build here

FROM ft-rails:on-build
EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]
